name: Deploy preview
on: workflow_dispatch
jobs:
    Deploy:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run: python -m pip install -r ./scripts/requirements.txt
            - run: python ./scripts/deploy.py --project FluentFuzzy --config Release --nuget-api-key ${{ secrets.NUGET_API_KEY }}
            