name: Test
on: 
    pull_request: { branches: [ develop, main, master ] }
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: python -m pip install -r ./scripts/requirements.txt
            - run: python ./scripts/test.py
            - run: echo "Done!"