name: PR to Main

on:
  pull_request:
    branches:
      - main

jobs:   
    run-tests:
        name: Run Tests
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run: python -m pip install -r ./scripts/requirements.txt
            - run: python ./scripts/test.py
            - run: echo "Done!"

    push-nuget:
        name: Push to Nuget (preview)
        needs: run-tests
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run: python -m pip install -r ./scripts/requirements.txt
            - run: python ./scripts/deploy.py --project FluentFuzzy --config Debug --nuget-api-key ${{ secrets.NUGET_API_KEY }}
