name: PR to Main

on:
  pull_request:
    branches:
      - main

jobs:   
    embed-code:
        name: Embed code snippets in readme
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: urmzd/embed-md@v1.0.0
              with:
                markdown-files: "README.md"
                commit-message: "chore: embed example using self"

    run-tests:
        name: Run Tests
        needs: embed-code
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run: python -m pip install -r ./scripts/requirements.txt
            - run: python ./scripts/test.py
            - run: echo "Done!"

    push-nuget:
        name: Push to Nuget (preview)
        needs: run-tests
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run: python -m pip install -r ./scripts/requirements.txt
            - run: python ./scripts/deploy.py --project FluentFuzzy --config Debug --nuget-api-key ${{ secrets.NUGET_API_KEY }}
